package com.mercer.scheduler.form.lov;
import oracle.forms.properties.ID;
public class testLov {
    public static void main(String[] args) {
        boolean call;
        MultiCheckBoxList mcbl=new MultiCheckBoxList();
       call= mcbl.setProperty(mcbl.SET_TITLE, "List of Companies");
       call= mcbl.setProperty(mcbl.SET_X, 200);
       call= mcbl.setProperty(mcbl.SET_Y, 100);
      call=  mcbl.setProperty(mcbl.SET_COLUMN_HEADER, "Company No");
     call=   mcbl.setProperty(mcbl.SET_COLUMN_HEADER, "Company Name");
      call=  mcbl.setProperty(mcbl.SET_COLUMN_HEADER, "Selected");
      call=  mcbl.setProperty(mcbl.ADD_ID, "AU01");
      call=  mcbl.setProperty(mcbl.ADD_ID, "CA01");
     call=   mcbl.setProperty(mcbl.ADD_ID, "US01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "AU01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "CA01");
        call=   mcbl.setProperty(mcbl.ADD_ID, "US01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "AU01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "CA01");
        call=   mcbl.setProperty(mcbl.ADD_ID, "US01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "AU01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "CA01");
        call=   mcbl.setProperty(mcbl.ADD_ID, "US01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "AU01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "CA01");
        call=   mcbl.setProperty(mcbl.ADD_ID, "US01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "AU01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "CA01");
        call=   mcbl.setProperty(mcbl.ADD_ID, "US01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "AU01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "CA01");
        call=   mcbl.setProperty(mcbl.ADD_ID, "US01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "AU01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "CA01");
        call=   mcbl.setProperty(mcbl.ADD_ID, "US01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "AU01");
        call=  mcbl.setProperty(mcbl.ADD_ID, "CA01");
        call=   mcbl.setProperty(mcbl.ADD_ID, "US01");
    
      call=  mcbl.setProperty(mcbl.ADD_DESC, "AA02 - Mercer Benefit Services Pty Ltd - INACTIVE");
      call=  mcbl.setProperty(mcbl.ADD_DESC, "AE01 - Mercer Consulting Middle East Limited");
      call=  mcbl.setProperty(mcbl.ADD_DESC, "AE02 - Mercer Financial Services Middle East Limited");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "AR01 - Mercer (Argentina) SA");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "AR02 - Mercer Asesores de Seguros S.A.:");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "AT01 - Mercer (Austria) GmbH");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "AU00 - Mercer (Australia) Pty Ltd");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "AU01 - Mercer Consulting (Australia) Pty Ltd");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "AU04 - Mercer Superannuation (Australia) Limited");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "AU07 - Mercer Investments (Australia) Ltd");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "AU08 - Mercer Outsourcing (Australia) Pty Ltd");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "AU09 - Mercer Financial Advice (Australia) Pty Ltd");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "BE01 - Mercer (Belgium) SA-NV");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "BR01 - Mercer Consulting (Brazil) Ltda");
        call=   mcbl.setProperty(mcbl.ADD_DESC, "BR02 - Mercer Corretora de Seguros");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "BR03 - Gama Consultores Associados Ltda.");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "CA01 - Mercer (Canada)  Limited");
        call=   mcbl.setProperty(mcbl.ADD_DESC, "CA45 - Mercer Global Investments Canada");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "CH01 - Mercer (Switzerland) SA");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "CH02 - Mercer Private Markets AG");
        call=   mcbl.setProperty(mcbl.ADD_DESC, "CL01 - Mercer Consulting (Chile) Ltda.");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "CL02 - Mercer Corredores de Seguros Limitada");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "CN01 - Mercer Consulting (China) Ltd.");
        call=   mcbl.setProperty(mcbl.ADD_DESC, "CO01 - Mercer (Colombia) Ltda.");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "CO02 - Mercer Agencia de Seguros Ltda");
        call=  mcbl.setProperty(mcbl.ADD_DESC, "CZ01 - Mercer (Czech) a.s.");
        call=   mcbl.setProperty(mcbl.ADD_DESC, "DE01 - Mercer Deutschland GmbH");
       // call=   mcbl.setProperty(mcbl.ADD_DESC, "DS01 - Mercer Deutschland GmbH");
        call=  mcbl.setProperty(mcbl.SHOW_MCHECKBOXLIST, true);
        call=  mcbl.setProperty(mcbl.CLEAR, "ALL");
        
    }
}
